name = "webbuilder-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "platform-db"
database_id = "cd72717d-5eb7-4106-9dad-6c26405509ad"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "project-assets"

[dev]
port = 8787